### ISSUE TITLE
[FE] Implement Landing Page for Ansopedia Web App

### ISSUE THREAD

**Issue by ansopedia** [ansopedia/web-app#1]
### Overview:

As we kickstart the development of Ansopedia web app from scratch, the first step is to implement the landing page based on the initial design created in [Figma](https://www.figma.com/file/A4vqrOLH0wsbas2zG9LLX6/Ansopedia-Web-App?type=design&node-id=0%3A1&mode=design&t=g7fowfh3x04sYVbh-1). This will serve as the foundation for our application and help us establish best practices for future development.

![image](https://github.com/ansopedia/ansopedia-web-app/assets/123801647/614c13c3-9555-4d07-9347-4a0ac6a33277)

Proposed Changes:

- Convert the design elements from the Figma mockup into Next.js code.
- Set up the basic structure of the landing page including header, welcome section, features section.
- Use semantic HTML tags and follow accessibility standards to optimize for search engines and screen readers.

### Challenges:

The design in Figma is not yet completed, so some design decisions may need to be made during the implementation process.
This is the first implementation of the app, so we'll need to set up the development environment and project structure from scratch.

**Comment by mfscifly** [comment]
Hello, can I work on this?

**Comment by ansopedia** [comment]
@mfscifly, 

Absolutely, you're more than welcome to work on it!

**Comment by Ronit152** [comment]
Hi , Want to work on this
