### ISSUE TITLE
FE - Implement Reusable Checkbox Component

### ISSUE THREAD

**Issue by ansopedia** [ansopedia/web-app#8]
**Description:**

The current UI lacks a reusable checkbox component. This makes building forms and selecting options cumbersome and requires repetitive code. Implementing a dedicated checkbox component will improve code maintainability, consistency, and efficiency.

**Proposed Solution:**

Develop a reusable checkbox component that offers the following functionalities:

- **State Management:** Manages the checked state (on/off) of the checkbox.
- **User Interaction:** Handles user clicks or taps on the checkbox to toggle its state.
- **Prop-Driven:** Accepts props to configure the label text, initial checked state, and potentially other behaviors.
- **Accessibility:** Ensures the component is accessible for users with disabilities, following [WCAG](https://www.w3.org/WAI/standards-guidelines/wcag) guidelines.

[Figma](https://www.figma.com/file/VzCn8kaed5zrEOKdt4CyUU/Ansopedia-UI-Kit?type=design&node-id=0%3A1&mode=dev&t=lT6aBgpbdjxY1kRI-1)

![image](https://github.com/ansopedia/web-app/assets/90146483/3db68047-a9f8-4c0c-aaf2-47e163944278)

## Folder Structure

```
src
  components
    ui
      Checkbox
        Checkbox.tsx
        checkbox.module.scss
```

**Note:** Try to integrate [Legend State React](https://legendapp.com/open-source/state/intro/introduction/) For state management.

**Comment by Meet-Kalani** [comment]
I wanna do it!
